### ISSUE TITLE
How can i get a spesific share's scores

### ISSUE THREAD

**Issue by idrisyagci** [orsifrancesco/instagram-without-api#1]
Thanks to this API, we can only see the shares in the form of a timeline. How can we see how many likes or comments a specific post has?

**Comment by orsifrancesco** [comment]
Thank you for your feedback/request.. I will take a look to implement it in the next push :)
(I will let you know)

**Comment by orsifrancesco** [comment]
Sure to please you, fetchByIdUrl and fetchById just added in the new commit.. you can now get info for a specific post :)
