### ISSUE TITLE
cookie expired after few request

### ISSUE THREAD

**Issue by talha-rafique** [orsifrancesco/instagram-without-api#3]
Hi, 
i have tried this many times and Instagram cookies expired after a certain time and no. of requests.

whats the solution you have for this ?

**Comment by orsifrancesco** [comment]
Hi, could you be more specific about the quantity of requests you did? For security reasons I can guess Instagram "kills" your cookie if you "abuse" about it.
I tried using cookies from different browsers but I don't know why, from Chrome it looks more "stable" and hard to expire to me.. but it is just a feeling.

**Comment by orsifrancesco** [comment]
@talha-rafique actually there is a solution.. more cookies (from different instagram accounts) in one array.. every call you use a different cookie in loop ;)
