### ISSUE TITLE
Composer Support

### ISSUE THREAD

**Issue by paulhennell** [orsifrancesco/instagram-without-api#4]
Any chance you could package this up for packagist? Currently the install instructions are just `composer install` which does nothing. If you can submit it to https://packagist.org/ it can be installed / managed like other project packages rather then getting into my project source.

(Great work making this btw, I want to track basic stats per month from IG and they make it so annoying to do automatically)

**Comment by paulhennell** [comment]
Lol - came back to it to add manually and realised there is a package setup just wasn't showing when I searched packagist.

Probably should add 'composer require orsif/instagram-without-api` to the readme for clarification!

**Comment by orsifrancesco** [comment]
@paulhennell I think I will submit to https://packagist.org/ , thank you :)

**Comment by orsifrancesco** [comment]
@paulhennell added
https://packagist.org/packages/orsifrancesco/instagram-without-api 
`composer require orsifrancesco/instagram-without-api`
it works!! :)

thanks for your suggestion
